vich_uploader:
    db_driver: orm

    mappings:
       clients_images:
                uri_prefix: '%clients_images%'
                upload_destination: '%kernel.project_dir%/public/%clients_images%'
                namer : Vich\UploaderBundle\Naming\SmartUniqueNamer
